version: '3.8'
services:
  visum-db:
    container_name: visum-db
    restart: always
    image: postgres:12.4
    volumes:
      - visum-db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - visum-network

  visum-api:
    container_name: visum-api
    networks:
      - visum-network
    depends_on:
      - visum-db
    env_file:
      - .env

networks:
  visum-network:

volumes:
  visum-db:
