# Stage: Build
FROM maven:3.6.3-openjdk-17-slim
WORKDIR /visum
COPY pom.xml .

# Dependencies cache
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests=true

# Stage: Execute
FROM openjdk:17.0.2-slim
ENV VISUM=visum
WORKDIR /$VISUM
EXPOSE 8080
ADD scripts/wait-for-it.sh wait-for-it.sh
RUN chmod 700 /$VISUM/wait-for-it.sh
COPY --from=0 /$VISUM/target/*.jar /$VISUM/$VISUM.jar

# Environments
ENV DB_NAME=visum-db
ENV DB_PORT=5432

# Run and wait database
ENTRYPOINT bash ./wait-for-it.sh ${DB_NAME}:$DB_PORT -t 10 -- java -Dspring.profiles.active=dev -jar $VISUM.jar
