TRUNCATE TABLE movie CASCADE;

TRUNCATE TABLE actor CASCADE;

TRUNCATE TABLE director CASCADE;

TRUNCATE TABLE movie_review CASCADE;

TRUNCATE TABLE genre CASCADE;

TRUNCATE TABLE movie_metadata CASCADE;

TRUNCATE TABLE movie_viewing_history CASCADE;
